### ISSUE TITLE
A question for step 5 (Generate <.react> from RT stop counts <.rtsc>)

### ISSUE THREAD

**Issue by canfeng-HUA** [StructureFold2/StructureFold2#10]
Thanks a lot for your codes. However, I have some questions for Step 5 (Generate <.react> from RT stop counts <.rtsc>).

My experiment design is not so complicated. I only have a (-) reagent group and a (+) reagent group. I only want to know the RNA structure in the normal condition at this stage.

1),   Therefore can I still use your code to do the analysis? 
2),  Can I use the <.react> file generate at step 5.1 to do the downstream analysis? 
3),  Does Step 5.2 is required for my experiment?

**Comment by StructureFold2** [comment]
Hello!

1)Yes; you can calculate reactivity for a single structurome.

2)Yes, if everything is working and the data is good, the react file should be good to go.

3)If you only have a single condition, then step 5.2 is not necessary. What step 5.2 does is use a scale file output from one reactivity calculation (.scale)  when calculating reactivity in another set of (-/+) reagent samples from another condition, applying the same 2-8% normalization to the final reactivity scores between conditions such that the reactivity values are directly comparable. 

For one condition, run rtsc_to_react and use the resultant .react for all downstream analyses. This should produce both a .react and a .scale file, although you don't really need the .scale file.

For two conditions, run rtsc_to_react on the control condition (or whatever is closest), then use rtsc_to_react on the experimental condition with the -scale option, inputting the control scale file. This would read from the scale file rather than calculating a scale internally, thus both calculations would have their final values normalized to the same scale and be comparable. When the -scale option is used, it does not write a new scale file, as a new scale was never calculated. 

For 3 or more conditions, run rtsc_to_react on the control condition (or whatever is closest), then use rtsc_to_react on all the experimental conditions with the -scale option, inputting the control scale in each case. Thus any number of (-/+) reagent sets can all use the same scale.

**Comment by StructureFold2** [comment]
If that answers the question let me know and I will close the issue.

**Comment by canfeng-HUA** [comment]
Thanks a lot for your clearly explanation! I think I get what I want.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: StructureFold2 <notifications@github.com>
发送时间: Saturday, November 7, 2020 6:41:42 AM
收件人: StructureFold2/StructureFold2 <StructureFold2@noreply.github.com>
抄送: canfeng-HUA <huacanfeng@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [StructureFold2/StructureFold2] A question for step 5 (Generate <.react> from RT stop counts <.rtsc>) (#10)


If that answers the question let me know and I will close the issue.

―
